### ISSUE TITLE
文档目录问题

### ISSUE THREAD

**Issue by purebluesong** [ylxdzsw/Rest.jl#1]
文档里面看起来hook后面minx是个子目录，但是readthedocs显示是同级目录，是故意的吗？

**Comment by ylxdzsw** [comment]
主题级别是markdown标签定义的，我觉得这两个内容是同级的，所以markdown里都给的是3级。放在一个文件里只是我觉得两个主题相关性比较强，修改的时候可以上下参照不用切换文件。
