### ISSUE TITLE
Tag new version?

### ISSUE THREAD

**Issue by TotalVerb** [ylxdzsw/Rest.jl#2]
The last tagged version of Restful.jl does not work with JSON v0.6.0. However, current master does work (thanks to https://github.com/ylxdzsw/Restful.jl/commit/6867324a3ef8fbe5fb57a8a06c5e091a5d3399e4). Tagging a new version would fix compatibility.

Ref https://github.com/JuliaLang/METADATA.jl/pull/5398#issuecomment-226658651

**Comment by ylxdzsw** [comment]
Thanks for your reminder! I will tag it soon.
